using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PdoConverter
{
    class CountryToCode
    {
        private Dictionary<string, string> CountryMapping = new Dictionary<string, string>();

        public CountryToCode()
        {
            CountryMapping.Add("Afganistan", "6023");
            CountryMapping.Add("Albanië", "5034");
            CountryMapping.Add("Algerije", "6047");
            CountryMapping.Add("Amerikaans Samoa", "8002");
            CountryMapping.Add("Amerikaanse Maagdeneilanden", "7088");
            CountryMapping.Add("Andorra", "7005");
            CountryMapping.Add("Angola", "5026");
            CountryMapping.Add("Anguilla", "8036");
            CountryMapping.Add("Antigua en Barbuda", "8045");
            CountryMapping.Add("Argentinië", "7015");
            CountryMapping.Add("Armenië", "5054");
            CountryMapping.Add("Aruba", "5095");
            CountryMapping.Add("Ascension", "5055");
            CountryMapping.Add("Australië", "6016");
            CountryMapping.Add("Azerbajdsjan", "5097");
            CountryMapping.Add("Azoren", "5056");
            CountryMapping.Add("Bahama-eilanden", "6033");
            CountryMapping.Add("Bahrein", "5057");
            CountryMapping.Add("Bangladesh", "7084");
            CountryMapping.Add("Barbados", "7004");
            CountryMapping.Add("Belarus (Wit-Rusland)", "5098");
            CountryMapping.Add("België", "5010");
            CountryMapping.Add("Belize", "8017");
            CountryMapping.Add("Benin", "8023");
            CountryMapping.Add("Bermuda", "9048");
            CountryMapping.Add("Bhutan", "5058");
            CountryMapping.Add("Bolivia", "6015");
            CountryMapping.Add("Bondsrepubliek Duitsland", "9089");
            CountryMapping.Add("Bosnië-Herzegovina", "6065");
            CountryMapping.Add("Botswana", "5011");
            CountryMapping.Add("Brazilië", "6008");
            CountryMapping.Add("Brits Territorium in Antarctica", "7095");
            CountryMapping.Add("Brits Territorium in Indische Oceaan", "7096");
            CountryMapping.Add("Britse Maagdeneilanden", "7030");
            CountryMapping.Add("Brunei", "5042");
            CountryMapping.Add("Bulgarije", "7024");
            CountryMapping.Add("Burkina Faso", "5096");
            CountryMapping.Add("Burundi", "6001");
            CountryMapping.Add("Canada", "5001");
            CountryMapping.Add("Canarische eilanden", "6053");
            CountryMapping.Add("Caymaneilanden", "7092");
            CountryMapping.Add("Centrafrika", "9086");
            CountryMapping.Add("Chili", "5021");
            CountryMapping.Add("China", "6022");
            CountryMapping.Add("Christmaseiland", "8012");
            CountryMapping.Add("Cocoseilanden", "8013");
            CountryMapping.Add("Colombia", "5033");
            CountryMapping.Add("Comoren", "5060");
            CountryMapping.Add("Cookeilanden", "7097");
            CountryMapping.Add("Costa Rica", "7007");
            CountryMapping.Add("Cuba", "5006");
            CountryMapping.Add("Cyprus", "5040");
            CountryMapping.Add("Democratische Republiek Congo", "6069");
            CountryMapping.Add("Denemarken", "5015");
            CountryMapping.Add("Djibouti", "9087");
            CountryMapping.Add("Dominica", "8030");
            CountryMapping.Add("Dominicaanse Republiek", "7027");
            CountryMapping.Add("Duitsland", "9089");
            CountryMapping.Add("Egypte", "7014");
            CountryMapping.Add("El Salvador", "7032");
            CountryMapping.Add("Equatoriaalguinee", "9043");
            CountryMapping.Add("Eritrea", "9003");
            CountryMapping.Add("Estland", "7065");
            CountryMapping.Add("Etiopië", "5020");
            CountryMapping.Add("Faeröer", "8014");
            CountryMapping.Add("Falklandeilanden", "5061");
            CountryMapping.Add("Fiji", "6032");
            CountryMapping.Add("Filipijnen", "5027");
            CountryMapping.Add("Finland", "6002");
            CountryMapping.Add("Frankrijk", "5002");
            CountryMapping.Add("Frans Guyana", "5062");
            CountryMapping.Add("Frans Polynesië", "6054");
            CountryMapping.Add("Gabon", "6048");
            CountryMapping.Add("Gambia", "7008");
            CountryMapping.Add("Georgië", "6064");
            CountryMapping.Add("Ghana", "5024");
            CountryMapping.Add("Gibraltar", "6055");
            CountryMapping.Add("Grenada", "8008");
            CountryMapping.Add("Griekenland", "6003");
            CountryMapping.Add("Groenland", "5065");
            CountryMapping.Add("Grootbrittannië", "6039");
            CountryMapping.Add("Guadeloupe", "5066");
            CountryMapping.Add("Guam", "8001");
            CountryMapping.Add("Guatemala", "6004");
            CountryMapping.Add("Guinee", "7040");
            CountryMapping.Add("Guinee Bissau", "5072");
            CountryMapping.Add("Guyana", "6025");
            CountryMapping.Add("Haïti", "6041");
            CountryMapping.Add("Honduras", "7017");
            CountryMapping.Add("Hongarije", "5017");
            CountryMapping.Add("Ierland", "6007");
            CountryMapping.Add("IJsland", "6011");
            CountryMapping.Add("India", "7046");
            CountryMapping.Add("Indonesië", "6024");
            CountryMapping.Add("Internationaal gebied", "9999");
            CountryMapping.Add("Irak", "5043");
            CountryMapping.Add("Iran", "5012");
            CountryMapping.Add("Israël", "6034");
            CountryMapping.Add("Italië", "7044");
            CountryMapping.Add("Ivoorkust", "5030");
            CountryMapping.Add("Jamaica", "6017");
            CountryMapping.Add("Japan", "7035");
            CountryMapping.Add("Jemen", "5048");
            CountryMapping.Add("Johnston", "5080");
            CountryMapping.Add("Jordanië", "6042");
            CountryMapping.Add("Kaapverdië", "8025");
            CountryMapping.Add("Kambodja", "6031");
            CountryMapping.Add("Kameroen", "5035");
            CountryMapping.Add("Kanaaleilanden", "8034");
            CountryMapping.Add("Katar", "9037");
            CountryMapping.Add("Kazachstan", "5099");
            CountryMapping.Add("Kenya", "7002");
            CountryMapping.Add("Kiribati", "8027");
            CountryMapping.Add("Koeweit", "7045");
            CountryMapping.Add("Kongo", "9008");
            CountryMapping.Add("Kroatië", "5051");
            CountryMapping.Add("Kyrgyzstan", "6021");
            CountryMapping.Add("Laos", "5025");
            CountryMapping.Add("Lesotho", "7016");
            CountryMapping.Add("Letland", "7064");
            CountryMapping.Add("Libanon", "7043");
            CountryMapping.Add("Liberia", "5019");
            CountryMapping.Add("Libië", "6006");
            CountryMapping.Add("Liechtenstein", "6012");
            CountryMapping.Add("Litouwen", "7066");
            CountryMapping.Add("Luxemburg", "6018");
            CountryMapping.Add("Macedonië", "5100");
            CountryMapping.Add("Madagaskar", "9010");
            CountryMapping.Add("Madeira-eilanden", "7087");
            CountryMapping.Add("Malawi", "5005");
            CountryMapping.Add("Maldiven", "7041");
            CountryMapping.Add("Maleisië", "7026");
            CountryMapping.Add("Mali", "5029");
            CountryMapping.Add("Malta", "7003");
            CountryMapping.Add("Man", "8035");
            CountryMapping.Add("Marianen", "8009");
            CountryMapping.Add("Marokko", "5022");
            CountryMapping.Add("Marshalleilanden", "9056");
            CountryMapping.Add("Martinique", "5069");
            CountryMapping.Add("Mauritanië", "6020");
            CountryMapping.Add("Mauritius", "5044");
            CountryMapping.Add("Mayotte", "5084");
            CountryMapping.Add("Mexico", "7006");
            CountryMapping.Add("Micronesia", "9094");
            CountryMapping.Add("Midway", "8003");
            CountryMapping.Add("Moldavië", "6000");
            CountryMapping.Add("Monaco", "5032");
            CountryMapping.Add("Mongolië", "7052");
            CountryMapping.Add("Montenegro", "5104");
            CountryMapping.Add("Montserrat", "8015");
            CountryMapping.Add("Mozambique", "5070");
            CountryMapping.Add("Myanmar", "5047");
            CountryMapping.Add("Namibië", "9023");
            CountryMapping.Add("Nauru", "7057");
            CountryMapping.Add("Nederland", "6030");
            CountryMapping.Add("Nederlandse Antillen", "7011");
            CountryMapping.Add("Nepal", "6035");
            CountryMapping.Add("Nicaragua", "7018");
            CountryMapping.Add("Nieuwcaledonië", "7099");
            CountryMapping.Add("Nieuwzeeland", "5013");
            CountryMapping.Add("Niger", "6040");
            CountryMapping.Add("Nigeria", "6005");
            CountryMapping.Add("Niue", "9091");
            CountryMapping.Add("Noord-Korea", "6049");
            CountryMapping.Add("Noorwegen", "6027");
            CountryMapping.Add("Norfolk", "8016");
            CountryMapping.Add("Oekraine", "6038");
            CountryMapping.Add("Oezbekistan", "6050");
            CountryMapping.Add("Oman", "7051");
            CountryMapping.Add("Onbekend", "0000");
            CountryMapping.Add("Oostenrijk", "5009");
            CountryMapping.Add("Pakistan", "7020");
            CountryMapping.Add("Panama", "7037");
            CountryMapping.Add("Panamakanaalzone", "8041");
            CountryMapping.Add("Papua-Nieuwguinea", "8021");
            CountryMapping.Add("Paraguay", "5038");
            CountryMapping.Add("Peru", "7049");
            CountryMapping.Add("Pitcairneilanden", "5071");
            CountryMapping.Add("Polen", "7028");
            CountryMapping.Add("Portugal", "7050");
            CountryMapping.Add("Puerto Rico", "8020");
            CountryMapping.Add("Republiek van Palau", "8044");
            CountryMapping.Add("Réunion", "5073");
            CountryMapping.Add("Roemenië", "7047");
            CountryMapping.Add("Rusland", "5053");
            CountryMapping.Add("Rwanda", "6009");
            CountryMapping.Add("Saint Kitts-Nevis", "8037");
            CountryMapping.Add("Saint Pierre en Miquelon", "5074");
            CountryMapping.Add("San Marino", "6028");
            CountryMapping.Add("São Tomé en Principe", "6059");
            CountryMapping.Add("Saoediarabië", "5018");
            CountryMapping.Add("Senegal", "7021");
            CountryMapping.Add("Servië", "5103");
            CountryMapping.Add("Seychellen", "8026");
            CountryMapping.Add("Sierra Leone", "6051");
            CountryMapping.Add("Singapore", "5037");
            CountryMapping.Add("Sint Helena", "6060");
            CountryMapping.Add("Sint Lucia", "8029");
            CountryMapping.Add("Sint Vincent en de Grenadinen", "5092");
            CountryMapping.Add("Slovenië", "5049");
            CountryMapping.Add("Slowakije", "6067");
            CountryMapping.Add("Soedan", "7034");
            CountryMapping.Add("Solomoneilanden", "8022");
            CountryMapping.Add("Somalia", "6013");
            CountryMapping.Add("Spanje", "6037");
            CountryMapping.Add("Sri Lanka", "7033");
            CountryMapping.Add("Suriname", "5007");
            CountryMapping.Add("Svalbardeilanden", "9095");
            CountryMapping.Add("Swaziland", "9036");
            CountryMapping.Add("Syrië", "7009");
            CountryMapping.Add("Tadzjikistan", "6057");
            CountryMapping.Add("Taiwan", "5052");
            CountryMapping.Add("Tanzania", "7031");
            CountryMapping.Add("Thailand", "7042");
            CountryMapping.Add("Tibet", "7055");
            CountryMapping.Add("Timor Leste", "5101");
            CountryMapping.Add("Toerkmenistan", "6063");
            CountryMapping.Add("Togo", "5023");
            CountryMapping.Add("Tokelau-eilanden", "7098");
            CountryMapping.Add("Tonga", "5076");
            CountryMapping.Add("Trinidad en Tobago", "6044");
            CountryMapping.Add("Tristan Da Cunha", "6061");
            CountryMapping.Add("Tsjaad", "6019");
            CountryMapping.Add("Tsjechië", "6066");
            CountryMapping.Add("Tunesië", "5008");
            CountryMapping.Add("Turkije", "6043");
            CountryMapping.Add("Turks- en Caicoseilanden", "8019");
            CountryMapping.Add("Tuvalu", "8028");
            CountryMapping.Add("Uganda", "7001");
            CountryMapping.Add("Uruguay", "7038");
            CountryMapping.Add("Vanuatu", "9090");
            CountryMapping.Add("Vaticaanstad", "5045");
            CountryMapping.Add("Venezuela", "6010");
            CountryMapping.Add("Verenigde Arabische Emiraten", "7054");
            CountryMapping.Add("Verenigde Staten van Amerika", "6014");
            CountryMapping.Add("Viëtnam", "8024");
        }

        public string GetCountryCode(String country){
            if (country == null)
                return "";

            string code = "";
            CountryMapping.TryGetValue(country, out code);
            return code;
        }
    }
}
