using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PdoConverter
{
    public partial class HelpForm : Form
    {

        String helpText = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\deflang1043{\\fonttbl{\\f0\\fnil\\fcharset0 Arial,Bold;}{\\f1\\fswiss\\fprq2\\fcharset0 Arial;}{\\f2\\froman\\fprq2\\fcharset0 Times New Roman;}{\\f3\\fswiss\\fprq2\\fcharset0 Calibri;}{\\f4\\fnil\\fcharset0 TheMixPVF;}{\\f5\\fnil\\fcharset136 Arial,BoldItalic;}{\\f6\\froman\\fprq2\\fcharset2 Symbol;}{\\f7\\fmodern\\fprq1\\fcharset0 Courier New;}{\\f8\\fnil\\fprq2\\fcharset2 Wingdings;}{\\f9\\fnil\\fcharset0 Arial,Italic;}{\\f10\\fnil\\fcharset0 Calibri;}}\n" +
    "{\\*\\generator Msftedit 5.41.21.2510;}\\viewkind4\\uc1\\pard\\b\\f0\\fs28 Technische beschrijving van het periodebestand\\par\n" +
    "\\b0\\f1\\fs20 Specificatie van het bestand dat t.b.v. deelnameregistratie StiPP aan PVF moet worden geleverd\\par\n" +
    "Naam bestand: PDOnnnnn .txt (nnnnn = volgnummer bestand door leverancier te \\par\n" +
    "bepalen)\\par\n" +
    "Type bestand: ASCII sequentieel\\par\n" +
    "Structuur bestand: 2 recordtypen:  type 1 is een voorlooprecord (per bestand 1 voorkomen) en \\par\n" +
    "type 2 is een detailrecord. Ieder record wordt afgesloten door een <carriage \\par\n" +
    "return>\\par\n" +
    "\\par\n" +
    "\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl VELDNAAM\\cell VELDTYPE\\cell VERPL.\\cell WAARDE\\cell TOELICHTING\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Code recordtype\\cell 1(N)\\cell J\\f3\\fs22\\cell\\f1\\fs20 1\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Naam gegevensleverancier\\cell 42(A)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Volgnummer bestand\\cell 5(N)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Datum aanmaak\\cell 8(N)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell (eejjmmdd)\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Adres gegevensleverancier\\cell 50(A)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl E-mail adres\\cell 40(A)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Naam contactpersoon\\cell 40(A)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Telefoonnummer contactpersoon\\cell 11(A)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Controlegetal\\cell 18(N)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Valuta aanduiding\\cell 3(A)\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell EUR OF NLG\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Reserve\\cell 13\\cell J\\f3\\fs22\\cell\\f1\\fs20\\cell\\cell\\row\\pard\\par\n" +
    "\\f4\\par\n" +
    "\\b\\f5\\fs32 Toelichting recordtype 1\\par\n" +
    "\\pard\\fi-360\\li720\\b0\\f6\\fs20\\'b7\\tab\\f1 Algemeen\\par\n" +
    "\\pard\\fi-360\\li1440\\f7 o\\tab\\f1 De gegevensleverancier is degene die de aanlevering van de StiPP deelnamegegevens verzorgt. Dit kan zijn:\\par\n" +
    "\\pard\\fi-360\\li2160\\f8\\'a7\\tab\\f1 een administratiekantoor of servicebureau dat de administratie voor een werkgever uitvoert\\par\n" +
    "\\f8\\'a7\\tab\\f1 de werkgever zelf  \\line (in dit geval gelden de werkgevergegevens als gegevens voor de gegevensleverancier)  \\par\n" +
    "\\pard\\fi-360\\li1440\\f7 o\\tab\\f1 Numerieke rubrieken: links aanvullen met voorloopnullen\\par\n" +
    "\\f7 o\\tab\\f1 Alfanumerieke rubrieken: rechts aanvullen met  spaties\\par\n" +
    "\\f7 o\\tab\\f1 Het gebruik van ' in een rubriek is niet toegestaan\\par\n" +
    "\\f7 o\\tab\\f1 Gegevensleverancier levert in principe 1 bestand per periode voor de \\b\\f0 hele \\b0\\f1 StiPP-populatie zoals door hem wordt beheerd. Dit kan dus betekenen dat er in een bestand deelnamegegevens van meerdere werkgevers zitten\\par\n" +
    "\\f7 o\\tab\\f1 Indien een bestand opnieuw wordt aangeleverd (b.v. doordat PVF het bestand heeft geweigerd vanwege fouten), moet dit bestand dezelfde identificatie bezitten als het oorspronkelijke bestand.\\line (identificatie = naam gegevensleverancier, volgnummer bestand, datum aanmaak bestand) \\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 Datum aanmaak bestand\\line Deze datum is (mede) identificerend bij de verwerking van de deelnamegegevens door PVF. Elk bestand dat voor de StiPP deelname wordt aangeleverd moet voorzien worden van een  \\par\n" +
    "\\pard\\li720 datum aanmaak bestand, deze datum mag niet in een ander StiPP-bestand van deze gegevensleverancier gebruikt worden. \\par\n" +
    "Dit geldt niet voor een hernieuwde aanlevering van hetzelfde bestand.\\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 Volgnummer bestand\\par\n" +
    "\\pard\\li720 Dit volgnummer is bepalend voor de volgorde waarin gegevens verwerkt moeten worden. \\par\n" +
    "Het eerst aangeleverde bestand moet volgnummer 1 bezitten. Volgende aangeleverde bestanden moeten een volgnummer bezitten dat  1 hoger is dan het volgnummer uit het vorig aangeleverde bestand. \\par\n" +
    "Dit geldt niet voor een hernieuwde aanlevering van hetzelfde bestand.\\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 E-mail adres\\par\n" +
    "\\pard\\li720 Indien aanwezig is het van belang om dit aan te geven.\\par\n" +
    "Het e-mail adres kan gebruikt worden voor de communicatie met PVF inzake de aanlevering van de StiPP deelnamegegevens. Dit communicatiemiddel kan een bijdrage leveren om, indien nodig, een snelle afstemming tussen PVF en de gegevensleverancier te realiseren.\\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 Controlegetal\\par\n" +
    "\\pard\\li720 Om te kunnen controleren of alle records van type 2 in het bestand aanwezig zijn, wordt er een controlegetal bepaald en in het eerste record opgenomen. Het controlegetal bestaat uit de som van de absolute waarde van het Bedrag pensioengevend loon met daarbij opgeteld het aantal records van recordtype 2. \\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 Valuta aanduiding\\par\n" +
    "\\pard\\li720 Aanduiding van de valuta waarmee de opgavens worden gedaan (=EUR of NLG).\\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 Reserve\\par\n" +
    "\\pard\\li720 Aanvullen met spaties.\\par\n" +
    "\\pard\\f4\\par\n" +
    "\\par\n" +
    "\\b\\f5\\fs24 Recordtype 2\\par\n" +
    "\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl\\b0\\f1\\fs20 VELDNAAM\\cell VELDTYPE\\cell VERPL.\\cell WAARDE\\cell TOELICHTING\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Code recordtype\\cell 1(N)\\cell\\f3\\fs22 J\\cell\\f1\\fs20 2\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Code opdrachtgever\\cell 3(N)\\cell\\f3\\fs22 J\\cell\\f1\\fs20 950\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Nummer werkgever\\cell 8(N)\\cell\\f3\\fs22 J\\cell\\f1\\fs20\\cell Identificatie bij PVF\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Nummer contract\\cell 2(N)\\cell\\f3\\fs22 J\\cell\\f1\\fs20\\cell Identificatie bij PVF\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Periodenummer\\cell\\lang1036 2(N)\\lang1043\\cell\\f3\\fs22 J\\cell\\f1\\fs20\\cell\\lang1036 range = 01 t/m 12\\lang1043\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Periodejaar\\cell 4(N)\\cell\\f3\\fs22 J\\cell\\f1\\fs20\\cell (eejj)\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Sofinummer\\cell 9(N)\\cell\\f3\\fs22 J\\cell\\f1\\fs20\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Naam\\cell\\cell\\f3\\fs22 J\\cell\\lang1036\\f1\\fs20 25(A)\\lang1043\\cell\\lang1036 A t/m Z spatie\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl\\lang1043 Voorletters\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 6(A)\\cell aaneengesloten letters\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Voorvoegsels\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 10(A)\\cell geen punten, \\lang1036 A t/m Z spatie\\lang1043\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Geboortedatum\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 8(N)\\cell (eejjmmdd)\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Code geslacht\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 1(N)\\cell man = 1,  vrouw = 2\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Huisnummer\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 5(N)\\cell (00005)\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl toevoeging\\cell\\cell\\f3\\fs22 J\\cell\\lang1033\\f1\\fs20 4(A)\\lang1043\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Postcode\\cell\\cell\\f3\\fs22 J\\cell\\lang1033\\f1\\fs20 6(A)\\lang1043\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl\\lang1033 Omschrijving adres\\lang1043\\cell\\cell\\f3\\fs22 J\\cell\\lang1033\\f1\\fs20 35(A)\\lang1043\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Postcode & plaats\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 35(A)\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Code land\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 4(A)\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Naam land\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 40(A)\\cell\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl Duur\\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 4(N)\\cell Duur in uren\\cell\\row\\trowd\\trgaph70\\trleft-108\\trbrdrl\\brdrs\\brdrw10 \\trbrdrt\\brdrs\\brdrw10 \\trbrdrr\\brdrs\\brdrw10 \\trbrdrb\\brdrs\\brdrw10 \\trpaddl70\\trpaddr70\\trpaddfl3\\trpaddfr3\n" +
    "\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx2835\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx4253\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx5387\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx6663\\clbrdrl\\brdrw10\\brdrs\\clbrdrt\\brdrw10\\brdrs\\clbrdrr\\brdrw10\\brdrs\\clbrdrb\\brdrw10\\brdrs \\cellx9214\\pard\\intbl pensioengevend loon \\cell\\cell\\f3\\fs22 J\\cell\\f1\\fs20 19(N)\\cell Bedrag in centen\\cell\\row\\pard\\par\n" +
    "\\lang1033\\par\n" +
    "\\lang1043\\b\\f5\\fs32 Toelichting recordtype 2\\par\n" +
    "\\pard\\fi-360\\li720\\b0\\i0\\f6\\fs20\\'b7\\tab\\f1 Algemeen\\par\n" +
    "\\pard\\fi-360\\li1440\\f7 o\\tab\\f1 Numerieke rubrieken: links aanvullen met voorloopnullen\\par\n" +
    "\\f7 o\\tab\\f1 Alfanumerieke rubrieken: rechts aanvullen met spaties\\par\n" +
    "\\f7 o\\tab\\f1 Het gebruik van ' in een rubriek is niet toegestaan\\par\n" +
    "\\f7 o\\tab\\f1 Indien deelnemergegevens worden aangeboden moet een binnenlands- \\b\\f0 of \\b0\\f1 een buitenlands adres aangegeven worden\\par\n" +
    "\\f7 o\\tab\\f1 Correcties\\par\n" +
    "\\pard\\fi-360\\li2160\\f8\\'a7\\tab\\f1 Correctie-opgaven mogen bij elke  aanlevering worden toegevoegd\\par\n" +
    "\\f8\\'a7\\tab\\f1 Het wissen van een geregistreerde periode-opgave voor een deelnemer kan bewerkstelligd worden door het plaatsen van de waarde 0  in de rubrieken duur \\b\\f0 en \\b0\\f1 bedrag pensioengevend loon\\par\n" +
    "\\f8\\'a7\\tab\\f1 Wanneer een opgave voor een bepaalde deelnemer in een voorgaand periodebestand te hoog is opgegeven dan kan dit gecorrigeerd worden in het eerstvolgende periodebestand. \\par\n" +
    "\\f8\\'a7\\tab\\f1 Men geeft dan bij deze persoon een negatief pensioengevendloon en een negatieve duur mee (een MIN .-. bedrag \\b\\f0\\'e8n \\b0\\f1 duur). Dit bedrag wordt vervolgens van de voorgaande opgaves afgetrokken. Mits dit uiteraard om opgaves gaat van dezelfde werkgever aansluitnummer/contract\\par\n" +
    "\\f8\\'a7\\tab\\f1 Indien er een opgave wordt gedaan voor een bepaalde periode en de deelnemer komt reeds voor in de PVF StiPP-administratie voor deze periode, dan wordt deze opgave als zijnde een correctie verwerkt\\par\n" +
    "\\pard\\fi-360\\li720\\f6\\'b7\\tab\\f1 Contract identificatie:\\line Wanneer het aansluitnummer 950-12345678-02-01 is, dan is 12345678 het Werkgevernummer en 01 het contractnummer. De identificatie van het contract moet in ieder record herhaald worden\\par\n" +
    "\\f6\\'b7\\tab\\f1 Periode identificatie:\\line Het periodenummer is af te leiden uit bijgaande kalender, het Periodejaar is het viercijferige jaartal. De identificatie van de periode moet in ieder record herhaald worden\\par\n" +
    "\\f6\\'b7\\tab\\f1 Binnenlands adres:\\line Nadere aanduiding huisnummer: de aanvullende gegevens van het huisnummer, b.v. A, 4h. \\i\\f9 Bij een binnenlands adres mogen er geen rubrieken van het buitenlandse adres gevuld zijn\\i0\\f1\\par\n" +
    "\\f6\\'b7\\tab\\f1 Buitenlands adres:\\line\\ul Omschrijving adres\\ulnone\\line Straatnaam en huisnummer                    \\b\\f0 OF\\line\\b0\\f1 Aanduiding P.O.B. of andere aanduiding voor postbus  \\b\\f0 EN\\line\\b0\\f1 Postbusnummer\\line\\ul Omschrijving postcode en plaats\\ulnone\\line Postcode en plaatsnaam\\line\\ul Code land\\line\\ulnone Code is afkomstig uit een gegevensverzameling door de overheid centraal beheerd in de BPR administratie. Deze tabel wordt ook gebruikt voor de gemeentelijke basis administratie (GBA) en is bij de gemeenten bekend. Aan het einde van dit document is een overzicht opgenomen waarin staat welke code bij welk land hoort. \\line\\i\\f9 Bij een buitenlands adres mogen er geen rubrieken van het binnenlandse adres gevuld zijn\\i0\\f1\\par\n" +
    "\\f6\\'b7\\tab\\f1 Deelname gegevens:\\line\\ul Duur\\line\\ulnone Dit is het aantal gewerkte uren in de periode. Als criterium voor de aanlevering van de gewerkte uren geldt dat de uren worden aangeleverd voor dezelfde looncomponenten als die meedoen in de bepaling van de pensioengrondslag dus inclusief de uren die betrekking hebben op reserveringen op het moment van uitbetalen.\\line\\ul Bedrag pensioengevend loon\\line\\ulnone Dit bestaat uit de gecumuleerde weeksalarissen zoals omschreven in het pensioenreglement;\\line\\line Het brutoloon bestaat voor de \\b\\f0 Basisregeling \\b0\\f1 uit:\\par\n" +
    "\\pard\\fi-360\\li1440\\f7 o\\tab\\f1 het loon over de normale gewerkte uren, \\par\n" +
    "\\f7 o\\tab\\f1 loon over de onregelmatige uren (de uren in afwijkende dag- en tijdzones), \\par\n" +
    "\\f7 o\\tab\\f1 indien tijdens ziekte loon wordt doorbetaald: het werkelijk door de werkgever doorbetaalde loon,\\par\n" +
    "\\f7 o\\tab\\f1 de vergoeding wegens loonderving van (een) wachtdag(en) in geval van ziekte ('wachtdagcompensatie'),\\par\n" +
    "\\f7 o\\tab\\f1 de uitbetaalde reserveringen voor vakantiedagen, bijzonder verlof, kort verzuim en feestdagen (indien van toepassing), en \\par\n" +
    "\\f7 o\\tab\\f1 de vakantiebijslag. \\par\n" +
    "\\pard\\fi708 Het brutoloon bestaat voor de \\b\\f0 Plusregeling \\b0\\f1 uit: \\par\n" +
    "\\pard\\fi-360\\li1440\\f7 o\\tab\\f1 het loon over de normale gewerkte uren,\\par\n" +
    "\\f7 o\\tab\\f1 het loon over de onregelmatige uren (de uren in afwijkende dag- en tijdzones), \\par\n" +
    "\\f7 o\\tab\\f1 indien tijdens ziekte loon wordt doorbetaald: het werkelijk door de werkgever doorbetaalde loon,\\par\n" +
    "\\f7 o\\tab\\f1 het loon over vakantiedagen, bijzonder verlof, kort verzuim en feestdagen (indien van toepassing), en \\par\n" +
    "\\f7 o\\tab\\f1 de vakantiebijslag. \\par\n" +
    "\\pard Onder brutoloon wordt niet verstaan het loon over overuren of compensatie-uren. Reisuren en \\par\n" +
    "gebruteerde kostenvergoedingen vallen ook niet onder het brutoloon. Let op, het loonbegrip is \\par\n" +
    "gewijzigd ten opzichte van het loonbegrip dat tot 1 januari 2008 werd gehanteerd. \\par\n" +
    "\\b\\f0\\par\n" +
    "Let op:\\par\n" +
    "\\b0\\f1 De pensioenopbouw over de reserveringen is gewijzigd ten opzichte van de oude regeling van de \\par\n" +
    "Stiplu tot 1 januari 2008. In de oude regeling werd pensioen opgebouwd over de opbouw van de \\par\n" +
    "\\pard\\sa200\\sl276\\slmult1 reserveringen, vanaf 2008 is dat over de uitbetaling van deze reserveringen.\\f3\\fs22\\par\n" +
    "\\pard\\sa200\\sl276\\slmult1\\lang19\\f10\\par\n" +
    "}";

        public HelpForm()
        {
            InitializeComponent();
            richTextBoxHelp.Rtf = helpText;
        }
    }
}
